course = 'Python for Beginners'
print(len(course))
print(course.upper())
print(course.lower())
print(course.find('P'))
print(course.find('o'))
print(course.find('Beginners'))
print(course.find('O'))
print(course.replace('Beginners', 'Absolute Beginners'))
print(course.replace('P', 'J'))
print('Python' in course)
print('python' in course)
print(course.title())